language: php

php:
  - 7.4
  - master

matrix:
  allow_failures:
    - php: master

before_script:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

script:
  - composer check
